version: '3.8'

services:
  train:
    build:
      context: model-train
      dockerfile: Dockerfile.train
    volumes:
      - mnist:/workspace/model
      - mnist:/workspace/data
    restart: on-failure

  evaluate:
    build:
      context: model-eval
      dockerfile: Dockerfile.eval
    volumes:
      - mnist:/workspace/model
      - mnist:/workspace/data
    restart: on-failure

  infer:
    build:
      context: model-inference
      dockerfile: Dockerfile.infer
    volumes:
      - mnist:/workspace/
    restart: on-failure

volumes:
  mnist: